# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\"\x1e\n\tAudioFile\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\" \n\nAudioChunk\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\".\n\x15TranscriptionResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t2\xa2\x01\n\tAIService\x12G\n\x0bUploadAudio\x12\x15.ai_service.AudioFile\x1a!.ai_service.TranscriptionResponse\x12L\n\x0bStreamAudio\x12\x16.ai_service.AudioChunk\x1a!.ai_service.TranscriptionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFILE']._serialized_start=32
  _globals['_AUDIOFILE']._serialized_end=62
  _globals['_AUDIOCHUNK']._serialized_start=64
  _globals['_AUDIOCHUNK']._serialized_end=96
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_start=98
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_end=144
  _globals['_AISERVICE']._serialized_start=147
  _globals['_AISERVICE']._serialized_end=309
# @@protoc_insertion_point(module_scope)
